project:
  type: website
  output-dir: docs

website:
  title: "Football + Data Science"
  site-url: "https://gaurang23.github.io/football-ds-blog/"
  navbar:
    right:
      # - text: "About"
      #   href: about.qmd
      - icon: github
        href: "https://github.com/gaurang23/football-ds-blog/"
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



